In [1]:
import numpy as np

dataTypes & Attributes

In [2]:
#main advantage of numpy is n D Array

a1=np.array([1,2,3])

In [3]:
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2=np.array([[1,2.0,3.1],
            [4,5,6.5]])

In [6]:
a2

array([[1. , 2. , 3.1],
       [4. , 5. , 6.5]])

In [7]:
a3=np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
             [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [8]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [9]:
a1.shape

(3,)

In [10]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
a1.ndim

1

In [13]:
a2.ndim

2

In [14]:
a3.ndim

3

In [15]:
a1.dtype

dtype('int32')

In [16]:
a2.dtype

dtype('float64')

In [17]:
a3.dtype

dtype('int32')

In [18]:
a1.size

3

In [19]:
a2.size

6

In [20]:
a3.size

18

In [21]:
type(a1)

numpy.ndarray

In [22]:
type(a2)

numpy.ndarray

In [23]:
type(a3)

numpy.ndarray

#creating Dataframe from Numpy Array

In [24]:
import pandas as pd

In [25]:
df=pd.DataFrame(a2)

In [26]:
df

0    1    2
0  1.0  2.0  3.1
1  4.0  5.0  6.5

#Creating arrays

In [27]:
sample_array=np.array([1,2,3])

In [28]:
sample_array

array([1, 2, 3])

In [29]:
sample_array.dtype

dtype('int32')

In [31]:
ones=np.ones((2,3))

In [32]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [33]:
ones.dtype()

TypeError: 'numpy.dtype' object is not callable

In [34]:
dtype(ones)

NameError: name 'dtype' is not defined

In [35]:
ones.dtype

dtype('float64')

In [36]:
type(ones)

numpy.ndarray

In [37]:
zeros=np.zeros((2,3))

In [38]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
zeros.dtype

dtype('float64')

In [41]:
type(zeros)

numpy.ndarray

In [42]:
range_array=np.arange(0,10,2)

In [43]:
range_array

array([0, 2, 4, 6, 8])

In [44]:
random_array=np.random.randint(1,10, size=(3,5))

In [45]:
random_array

array([[9, 1, 5, 5, 1],
       [7, 1, 3, 7, 4],
       [6, 5, 4, 6, 7]])

In [47]:
random_array2=np.random.random((5,3))

In [48]:
random_array2

array([[0.42652187, 0.71643381, 0.74682751],
       [0.24342989, 0.04031358, 0.50196113],
       [0.7078992 , 0.21825367, 0.47002474],
       [0.09813957, 0.17609615, 0.05920262],
       [0.09806694, 0.03733839, 0.17662202]])

In [50]:
random_array2.shape

(5, 3)

In [51]:
random_array3=np.random.rand(5,3)

In [52]:
random_array3

array([[0.5142508 , 0.71631857, 0.61779504],
       [0.45098968, 0.10074583, 0.15737493],
       [0.37981683, 0.91151438, 0.75366719],
       [0.87425741, 0.03955826, 0.70087245],
       [0.48176041, 0.7853662 , 0.67362181]])

In [53]:
random_array3.shape

(5, 3)

#pseudo random Numbers

In [58]:
np.random.seed(seed=1)
random_array4=np.random.randint(10,size=(5,3))

In [59]:
random_array4

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6],
       [9, 2, 4],
       [5, 2, 4]])

In [60]:
random_array4.shape

(5, 3)

In [61]:
np.random.seed(seed=7)
random_array5=np.random.random((5,3))

In [62]:
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [63]:
random_array5.shape

(5, 3)

#viewing arrays & Matrices

In [64]:
np.unique(random_array4)

array([0, 1, 2, 4, 5, 6, 7, 8, 9])

In [65]:
a2[1]

array([4. , 5. , 6.5])

In [67]:
a2[0]

array([1. , 2. , 3.1])

#Array Slicing

In [68]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [69]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [70]:
a4=np.random.randint(0,10, size=(2,3,4,5))

In [71]:
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [72]:
a4.shape

(2, 3, 4, 5)

In [73]:
a4.ndim

4

In [75]:
a4[:,:,:,:4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])